# Generated by Django 3.0.2 on 2020-03-07 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 19, 32, 11, 967413, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
